flags = {
    "Angola": "🇦🇴",
    "Bolivia": "🇧🇴",
    "Brazil": "🇧🇷",
    "Burundi": "🇧🇮",
    "Cameroon": "🇨🇲",
    "Central African Republic": "🇨🇫",
    "China": "🇨🇳",
    "Colombia": "🇨🇴",
    "Congo": "🇨🇬",
    "Costa Rica": "🇨🇷",
    "Cuba": "🇨🇺",
    "Dominican Republic": "🇩🇴",
    "Ecuador": "🇪🇨",
    "El Salvador": "🇸🇻",
    "Ethiopia": "🇪🇹",
    "Gabon": "🇬🇦",
    "Ghana": "🇬🇭",
    "Guatemala": "🇬🇹",
    "Guinea": "🇬🇳",
    "Haiti": "🇭🇹",
    "Honduras": "🇭🇳",
    "India": "🇮🇳",
    "Indonesia": "🇮🇩",
    "Ivory Coast": "🇨🇮",
    "Jamaica": "🇯🇲",
    "Kenya": "🇰🇪",
    "Laos": "🇱🇦",
    "Liberia": "🇱🇷",
    "Madagascar": "🇲🇬",
    "Malawi": "🇲🇼",
    "Mexico": "🇲🇽",
    "Nicaragua": "🇳🇮",
    "Nigeria": "🇳🇬",
    "Panama": "🇵🇦",
    "Papua New Guinea": "🇵🇬",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "Philippines": "🇵🇭",
    "Rwanda": "🇷🇼",
    "Sierra Leone": "🇸🇱",
    "Tanzania": "🇹🇿",
    "Thailand": "🇹🇭",
    "Timor-Leste": "🇹🇱",
    "Togo": "🇹🇬",
    "Trinidad and Tobago": "🇹🇹",
    "Uganda": "🇺🇬",
    "Venezuela": "🇻🇪",
    "Vietnam": "🇻🇳",
    "Yemen": "🇾🇪",
    "Zambia": "🇿🇲",
    "Zimbabwe": "🇿🇼",
}
